# Databricks Apps configuration for Lakebase Todo App
# https://docs.databricks.com/dev-tools/databricks-apps/app-runtime

command:
  - uvicorn
  - app:app
  - --host
  - "0.0.0.0"
  - --port
  - "8000"

env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: LAKEBASE_PROJECT_ID
    value: "todo-app"
  - name: LAKEBASE_BRANCH_ID
    value: "main"
  - name: LAKEBASE_ENDPOINT_ID
    value: "default"
  - name: LAKEBASE_DATABASE
    value: "postgres"
